### ISSUE TITLE
Request to update order of regions in _stats.txt file

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/LegacyIssueTracker#125]
As we plan to implement support in Nutil for the stats.txt (for all slices) in the future, it would be better if the regions were organised in the same way as the regions in the regions.txt output from QControl (organised based on the customised version of the hierarchy). It's fine to have the regions listed downwards, but all the regions should be included, even if they have no markers. Currently, there is a whole brain (all slices) stats report and separate slice reports. We will use the whole brain stats report for Nutil, so my request applies mainly to this one.

**Comment by Tevemadar** [comment]
Available in the updated release of V0.6.

**Comment by Majpuc** [comment]
@sharoncy could you validate if this is working? :)

**Comment by Majpuc** [comment]
Can we close this issue @sharoncy

**Comment by sharoncy** [comment]
Issue closed 20.03.23
