### ISSUE TITLE
Problem with hierarchy sheet from QCAlign

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/LegacyIssueTracker#150]
Hi @Tevemadar. Brianna and I have used QCAlign to generate a hierarchy sheet for defining customized regions in Nutil. However, we've found a bug: it's not fully compatible with Nutil. For example, the "dentate gyrus" is listed as one of the regions, but only includes ID 726. This ID is not assigned to any voxels in CCFv3 2015, which means that when it is used in Nutil, this customized region gives no output. This is confusing for users. Bigger regions like this should list all the IDs that are part of the region: in this case 10703, 10704 and 632, corresponding to the molecular, granule and polymorph layers that make up the dentate gyrus in CCFv3 2015; or be removed altogether (see my comment below).

![image](https://user-images.githubusercontent.com/30626642/158335837-18fa7b7e-9a0f-41d4-8932-68e3adb558c7.png)

![image](https://user-images.githubusercontent.com/30626642/158336935-94eefd11-5a70-434b-98b8-0fdcf2a39655.png)

To make the hierarchy sheet fully compatible with Nutil, issue 142 should also be fixed. Let me know if you have any questions. 
Thanks!

**Comment by sharoncy** [comment]
I did some more testing. I simplified the hierarchy so that the dentate gyrus is not subdivided and exported the corresponding hierarchy sheet: the dentate gyrus definition here is perfect, no problems. 
So instead of implementing my suggestion above, probably easier to remove broader regions from the hierarchy sheet when they have been subdivided into smaller parts. 
![image](https://user-images.githubusercontent.com/30626642/158343001-dca85848-9916-4e31-83f6-65ce68c1a277.png)

**Comment by sharoncy** [comment]
My mistake on the terminology. And thanks for QCAlign, I'll do some testing next week and get back.

**Comment by sharoncy** [comment]
I've done some testing. 
* The RGB colours look good. 
* There is some inconsistency between the regions listed in the hierarchy output sheet and the hierarchy selected in QCAlign. 
For example, I selected the hierarchy level shown in the screenshots and exported the hierarchy sheet. The hierarchy in QCAlign includes Ammon's horn and many thalamic nuclei (e.g. ventral group of the dorsal thalamus). But these are not included in the hierarchy sheet at all. 
* As an additional request, would you also update the naming of the files from QControl to QCAlign (the txt file below is an example)? 

![image](https://user-images.githubusercontent.com/30626642/161542779-388e61a8-4de5-4b50-8bdf-ed039a321121.png)

![image](https://user-images.githubusercontent.com/30626642/161542836-b7d32cb2-5f62-4b48-875a-25ba88fca830.png)

[M_QControl_Thionine_SY_regions_v080.txt](https://github.com/Neural-Systems-at-UIO/VisuAlign/files/8409642/M_QControl_Thionine_SY_regions_v080.txt)

Let me know if you need more info here. I can prepare an example dataset if this helps.

**Comment by sharoncy** [comment]
A final request is to add in a link to the readthedocs somewhere. Maybe in the help menu? https://qcalign.readthedocs.io

**Comment by Majpuc** [comment]
Has all this been resolved ? @Tevemadar @sharoncy

**Comment by sharoncy** [comment]
close 20.02.23.
