### ISSUE TITLE
Error - sliding bars on right hand side

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/LegacyIssueTracker#162]
Coordinates only appear in Meshview after adjusting the sliding bars on the left hand side. 

![Image](https://user-images.githubusercontent.com/30626642/172332984-ceaa039e-f2a3-4c03-9bd3-a82dd2754511.png)

**Comment by Majpuc** [comment]
Which version of MeshView are you refeering to? @sharoncy 
Where are the coordinates displayed?

**Comment by Majpuc** [comment]
Could you specify where you expect the coordinates to be displayed @sharoncy

**Comment by sharoncy** [comment]
I think this was fixed so let's close for now. 20.02.23
