### ISSUE TITLE
UX add help buttons and link to documentation

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/LegacyIssueTracker#177]

**Comment by Majpuc** [comment]
Documentation both inside and outside of the app: link to the webalign RtDocs

**Comment by Majpuc** [comment]
Yes, I am on it!

**Comment by Majpuc** [comment]
Preliminary Webwarp documentation in place

**Comment by Majpuc** [comment]
Which repo should be mentionned for reporting issues?
