### ISSUE TITLE
Realtime DZ to NG tiles service

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/LegacyIssueTracker#186]
28.009.2022 @Tevemadar is doing some tests on this one.
03.10.2022 Done. Sample https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B16312.8271484375%2C14317.1767578125%2C0.5%5D%2C%22crossSectionScale%22:79.4398395522613%2C%22projectionOrientation%22:%5B-0.002367608482018113%2C0.006638523191213608%2C0.005079911556094885%2C0.9999622702598572%5D%2C%22projectionScale%22:4096%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://dzing-dzing.apps-dev.hbp.eu/convert/https://object.cscs.ch/v1/AUTH_08c08f9f119744cbbf77e216988da3eb/imgsvc-7e9a11b7-b27f-67d7-95c8-3b72bb5086e9/D1R_P70_F_E15_s013.tif/D1R_P70_F_E15_s013.dzi%22%2C%22tab%22:%22source%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22D1R_P70_F_E15_s013.dzi%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22D1R_P70_F_E15_s013.dzi%22%7D%2C%22layout%22:%22xy%22%7D

**Comment by Tevemadar** [comment]
I prefer the one with color: https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B15963.2890625%2C14952.6962890625%2C0.5%5D%2C%22crossSectionScale%22:79.4398395522613%2C%22projectionOrientation%22:%5B-0.002367608482018113%2C0.006638523191213608%2C0.005079911556094885%2C0.9999622702598572%5D%2C%22projectionScale%22:4096%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://dzing-dzing.apps-dev.hbp.eu/convert/https://object.cscs.ch/v1/AUTH_08c08f9f119744cbbf77e216988da3eb/imgsvc-7e9a11b7-b27f-67d7-95c8-3b72bb5086e9/D1R_P70_F_E15_s013.tif/D1R_P70_F_E15_s013.dzi%22%2C%22tab%22:%22rendering%22%2C%22shader%22:%22void%20main%20%28%29%20%7B%5CnemitRGB%28vec3%28toNormalized%28getDataValue%280%29%29%2C%5CntoNormalized%28getDataValue%281%29%29%2C%5CntoNormalized%28getDataValue%282%29%29%29%29%3B%5Cn%7D%5Cn%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22D1R_P70_F_E15_s013.dzi%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22D1R_P70_F_E15_s013.dzi%22%7D%2C%22layout%22:%22xy%22%7D

**Comment by Majpuc** [comment]
DZing Service is created and can be used for Webilastik. Issue closed 20.02.2023
