### ISSUE TITLE
Meshes are disappearing when cut is activated

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/LegacyIssueTracker#193]

**Comment by Majpuc** [comment]
When both point clouds and meshes are active, if the user wants to cut the volume, only the point cloud is visible and cut. Is it possible to keep both? @Tevemadar

**Comment by Tevemadar** [comment]
I think this is about transparent meshes getting switched off when cutting is active.
Now transparent meshes go full opaque when cutting is active.
https://meshview.apps.hbp.eu/ and collab versions have this change.

**Comment by Majpuc** [comment]
Implemented. Issue closed
